# tasks file
---
- name: php | mods | memcache | update memcache.ini
  ansible.builtin.template:
    src: "{{ php_fpm_ondrej_php_mods_available_path.lstrip('/') }}/memcache.ini.j2"
    dest: "{{ php_fpm_ondrej_php_mods_available_path }}/memcache.ini"
    owner: root
    group: root
    mode: '0644'
  notify: reload apache2
